name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp-pure-form-7dzsf1/apps/website
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        env:
          CI: false

      - name: Verify dist
        run: |
          test -d dist || (echo "::error::dist не создан"; exit 1)
          ls -la dist

      # Линт после сборки и НЕ фейлит джобу
      - name: Lint (non-blocking)
        run: bun run lint || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webapp-pure-form-7dzsf1/apps/website/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
